language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
os:
  - linux
#  - osx
before_install:
  - python --version
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
# command to run tests
script:
  - coverage run --source cwlkernel --omit cwlkernel/__main__.py -m unittest discover tests
after_script:
  - coveralls
matrix:
  include:
    - name: "Python 3.6.5 on macOS 10.13"
      os: osx
      osx_image: xcode9.4  # Python 3.6.5 running on macOS 10.13
      language: shell  # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
        - pip3 install -U -r requirements.txt
        - pip3 install -U -r test-requirements.txt
      script: coverage run --source cwlkernel --omit cwlkernel/__main__.py -m unittest discover tests
